import test from 'node:test';
import assert from 'node:assert/strict';
import {makeHandler} from './campaign.mjs';
const env={OPENAI_API_KEY:'test-secret',LAUNCHSCAPE_ACCESS_TOKEN:'office-test'};
const draft=Object.fromEntries(['name','audience','offer','positioning','emailSubject','emailBody','callScript','socialPost','followUp','actionPlan'].map(k=>[k,'Draft '+k]));
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(b){this.body=b;return this;},end(){return this;}};}
const req=(changes={})=>({method:'POST',headers:{origin:'https://ncse1.github.io',authorization:'Bearer office-test'},body:{audience:'Waterfront homeowners',goal:'Book consultations'},...changes});
test('unauthorized requests never call OpenAI',async()=>{let called=false;const res=response();await makeHandler({env,fetcher:()=>{called=true;}})(req({headers:{authorization:'Bearer wrong'}}),res);assert.equal(res.code,401);assert.equal(called,false);});
test('rejects unapproved origins and allows preflight',async()=>{let res=response();await makeHandler({env})(req({headers:{origin:'https://attacker.example'}}),res);assert.equal(res.code,403);res=response();await makeHandler({env})(req({method:'OPTIONS'}),res);assert.equal(res.code,204);assert.equal(res.headers['Access-Control-Allow-Origin'],'https://ncse1.github.io');});
test('successful requests keep key server-side and exclude lead records',async()=>{let payload;const res=response();await makeHandler({env,fetcher:async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer test-secret');payload=JSON.parse(options.body);return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(draft)}]}]})};}})(req({body:{audience:'Waterfront owners',goal:'Consultations',leads:[{phone:'private-phone'}]}}),res);assert.equal(res.code,200);assert.deepEqual(res.body,{campaign:draft});assert.equal(payload.store,false);assert.ok(!payload.input.includes('private-phone'));assert.ok(!JSON.stringify(res.body).includes('test-secret'));});
test('handles quota limits without returning provider details',async()=>{const res=response();await makeHandler({env,fetcher:async()=>({ok:false,status:429})})(req(),res);assert.equal(res.code,429);assert.match(res.body.error,/usage or rate limit/);});
test('rejects malformed and incomplete AI output',async()=>{for(const output of [{status:'incomplete'},{status:'completed',output:[{content:[{type:'output_text',text:'{}'}]}]}]){const res=response();await makeHandler({env,fetcher:async()=>({ok:true,json:async()=>output})})(req(),res);assert.equal(res.code,502);}});
test('requires configuration and input',async()=>{let res=response();await makeHandler({env:{}})(req(),res);assert.equal(res.code,503);res=response();await makeHandler({env})(req({body:{}}),res);assert.equal(res.code,400);});
